### ISSUE TITLE
/page/start

### ISSUE THREAD

**Issue by yelizariev** [kaerdsar/odoo-saas-tools#3]
Something should be done with modules
- saas_pricing 
- saas_portal
1. Both of them has the same main.js file.
2. saas_portal define /page/start template, but it doesn't work without controller that is defined in saas_pricing

I think all /page/start stuff should be moved to one of modules. I can do it myself, but I am not sure to which one.

**Comment by yelizariev** [comment]
1. both of them has the same /saas_portal/book_then_signup contoller

**Comment by kaerdsar** [comment]
saas_pricing is not working now, maybe we can work on in later. I think all stuff must be in saas_portal

**Comment by kaerdsar** [comment]
In the solution a user can create many tenants. In my idea you sign up in the platform and get a tenant, so I'm not using /page/start and I redirect to /book_then_singup after sign up. Ideas?

**Comment by yelizariev** [comment]
This is example of my idea for this tools -- everyone can built saas system with a features he need.

We can move page/start to saas_start module.

**Comment by kaerdsar** [comment]
I agree with that new module. In saas_start we can include some configuration to decide if create a tenant with sign up or direct in page /start. Or maybe the default behaviour is create a tenant after sign up and the new module offers to change this.

**Comment by yelizariev** [comment]
Maybe create tenant with sign up should be also in a separate module and in saas_portal only technical stuff should be keepd.

Names of modules can be:
- saas_portal
- saas_portal_start
- saas_portal_signup

**Comment by kaerdsar** [comment]
Ok. I created a branch develop. Can we use that one?

**Comment by yelizariev** [comment]
I can create such updates in my repo and then create Pull Request. You will accept one only after testing. 
If you want create such updates yourself and don't want merge it before reviewing, you can upload such updates to develop branch.
